id: gm4_guidebook_example
name: Guidebook Example
version: 0.0.X

data_pack:
  load: .

pipeline:
  - gm4.plugins.extend.module

meta:
  gm4:
    website:
      hidden: true
      description: Adds a dynamic guidebook to discover the mechanics of Gamemode 4! This provides a wiki-like experience in-game!
      recommended:
        - gm4_resource_pack
      notes:
        - Experimental Module! Features may be added or removed without an easy upgrade path. You may encounter unintentional behaviour.
    video: null
    wiki: https://wiki.gm4.co/wiki/Guidebook
    credits:
      Creators:
        - BluePsychoRanger
        - JP12
